// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AitranslationController from "./aitranslation_controller"
application.register("aitranslation", AitranslationController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import TinymceController from "./tinymce_controller"
application.register("tinymce", TinymceController)

import TomselectController from "./tomselect_controller"
application.register("tomselect", TomselectController)
