// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AitranslationController from "./aitranslation_controller"
application.register("aitranslation", AitranslationController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import TomselectController from "./tomselect_controller"
application.register("tomselect", TomselectController)
