require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-faker

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 30

MultipleMemoizedHelpers:
  Max: 15

ExampleLength:
  Max: 30

NestedGroups:
  Max: 5

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Security/Eval:
  Exclude:
    - 'spec/services/posts/filter_spec.rb'
    - 'spec/services/posts/search_spec.rb'

RSpec/LetSetup:
  Exclude:
    - 'spec/services/posts/search_spec.rb'

Rails/CreateTableWithTimestamps:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
