height: 500
menubar: true
toolbar:
  - codesample nonbreaking | casechange blocks | bold italic | alignleft aligncenter alignjustify| bullist numlist checklist| undo redo | removeformat | restoredraft
plugins:
  - codesample advlist autolink autosave autoresize importcss lists link image charmap preview anchor searchreplace pagebreak nonbreaking visualblocks fullscreen insertdatetime media table code help wordcount
codesample_languages: [  
    { text: 'Ruby', value: 'ruby' },
    { text: 'HTML/XML', value: 'markup' },
    { text: 'JavaScript', value: 'javascript' },
    { text: 'CSS', value: 'css' }
  ]
skin: "oxide-dark"
language: uk
promotion: false
style_formats_merge: true
autoresize_bottom_margin: 50
min_height: 300
max_height: 700
nonbreaking_force_tab: true
